services:
    yarpapigateway:
        image: ${DOCKER_REGISTRY-}yarpapigateway
        build:
          context: .
          dockerfile: Gateways/YarpApiGateway/Dockerfile
    orderdb:
        image: mcr.microsoft.com/mssql/server
   
    order.api:
        image: ${DOCKER_REGISTRY-}orderapi
        build:
            context: .
            dockerfile: Services/Order/Order.Api/Dockerfile

    routing.grpc:
        image: ${DOCKER_REGISTRY-}routinggrpc
        build:
           context: .
           dockerfile: Services/Routing/Routing.gRPC/Dockerfile

